### ISSUE TITLE
Compile failure with base-4.7

### ISSUE THREAD

**Issue by hvr** [bartavelle/fastparser#1]
Hi, I noticed the compile failure below

```
Configuring component lib from fastparser-0.3.0...
Preprocessing library fastparser-0.3.0...
[1 of 1] Compiling ByteString.Parser.Fast ( src/ByteString/Parser/Fast.hs, /tmp/matrix-worker/1495789579/dist-newstyle/build/x86_64-linux/ghc-7.8.4/fastparser-0.3.0/build/ByteString/Parser/Fast.o )

src/ByteString/Parser/Fast.hs:130:10:
    Not in scope: type constructor or class ‘Monoid’
    Perhaps you meant ‘Monad’ (imported from Control.Monad)
```

(`Monoid` moved into Prelude only with base-4.8 as a side-effect of the FTP/AMP/Semigroup-Monoid proposals)

I already revised the meta-data at https://hackage.haskell.org/package/fastparser-0.3.0/revisions/ so there's no need to upload a new release just for the metadata.

**Comment by bartavelle** [comment]
Thanks a lot, I will fix that for the next revisions!
